version: '2'
services:
    divisioncompetition-app:
        image: divisioncompetition
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://divisioncompetition-mssql:1433;database=divisionCompetition
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    divisioncompetition-mssql:
        extends:
            file: mssql.yml
            service: divisioncompetition-mssql
