version: '2'
services:
    divisioncompetition-mssql:
        image: microsoft/mssql-server-linux:latest
        # volumes are not supported on macOS
        # volumes:
        #     - ~/volumes/jhipster/tempdb/mssql/:/var/opt/mssql/data/
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=1234
            - MSSQL_DATABASE=divisionCompetition
            - MSSQL_SLEEP=7
        ports:
            - 1433:1433
        command: /bin/bash -c '/opt/mssql/bin/sqlservr & echo "wait $$MSSQL_SLEEP sec for DB to start "; sleep $$MSSQL_SLEEP; /opt/mssql-tools/bin/sqlcmd -U div_comp_adm -P $$SA_PASSWORD -d tempdb -q "EXIT(CREATE DATABASE $$MSSQL_DATABASE)"; wait;'
